/** Tera Term 公式マニュアル v5 に基づくコマンド引数仕様 */
export interface CommandArgSpec {
  min: number
  /** null = 上限なし（可変長） */
  max: number | null
}

/**
 * 引数個数仕様（公式ドキュメント準拠）
 * https://teratermproject.github.io/manual/5/en/macro/command/
 */
export const COMMAND_ARG_SPECS: Record<string, CommandArgSpec> = {
  // ── 0 引数 ──
  end: { min: 0, max: 0 },
  exit: { min: 0, max: 0 },
  break: { min: 0, max: 0 },
  continue: { min: 0, max: 0 },
  return: { min: 0, max: 0 },
  next: { min: 0, max: 0 },
  endif: { min: 0, max: 0 },
  else: { min: 0, max: 0 },
  endwhile: { min: 0, max: 0 },
  enduntil: { min: 0, max: 0 },
  flushrecv: { min: 0, max: 0 },
  recvln: { min: 0, max: 0 },
  bplusrecv: { min: 0, max: 0 },
  kmtrecv: { min: 0, max: 0 },
  kmtfinish: { min: 0, max: 0 },
  quickvanrecv: { min: 0, max: 0 },
  ymodemrecv: { min: 0, max: 0 },
  zmodemrecv: { min: 0, max: 0 },
  logclose: { min: 0, max: 0 },
  logpause: { min: 0, max: 0 },
  logstart: { min: 0, max: 0 },
  closett: { min: 0, max: 0 },
  unlink: { min: 0, max: 0 },
  testlink: { min: 0, max: 0 },
  sendbreak: { min: 0, max: 0 },
  bringupbox: { min: 0, max: 0 },
  closesbox: { min: 0, max: 0 },

  // ── 可変長 ──
  send: { min: 0, max: null },
  sendln: { min: 0, max: null },
  sendbinary: { min: 0, max: null },
  sendtext: { min: 0, max: null },
  sendbroadcast: { min: 0, max: null },
  sendlnbroadcast: { min: 0, max: null },
  sendmulticast: { min: 1, max: null },
  sendlnmulticast: { min: 1, max: null },
  dispstr: { min: 1, max: null },
  sprintf: { min: 1, max: null },
  sprintf2: { min: 2, max: null },
  regexoption: { min: 1, max: null },
  listbox: { min: 3, max: null },

  // ── 範囲指定 ──
  wait: { min: 1, max: 10 },
  waitln: { min: 1, max: 10 },
  waitregex: { min: 1, max: 10 },
  wait4all: { min: 1, max: 10 },

  // ── 式 1 引数 ──
  if: { min: 1, max: 1 },
  while: { min: 1, max: 1 },
  until: { min: 1, max: 1 },
  elseif: { min: 1, max: 1 },

  // ── 制御 ──
  for: { min: 3, max: 3 },
  goto: { min: 1, max: 1 },
  /** 第1引数=ラベル、以降=サブルーチン引数（可変長） */
  call: { min: 1, max: null },
  include: { min: 1, max: 1 },
  execcmnd: { min: 1, max: 1 },
  pause: { min: 1, max: 1 },
  mpause: { min: 1, max: 1 },
  do: { min: 0, max: 2 },
  loop: { min: 0, max: 2 },

  // ── 通信 ──
  connect: { min: 1, max: 1 },
  cygconnect: { min: 0, max: 1 },
  disconnect: { min: 0, max: 1 },
  changedir: { min: 1, max: 1 },
  clearscreen: { min: 1, max: 1 },
  enablekeyb: { min: 1, max: 1 },
  gethostname: { min: 1, max: 1 },
  getmodemstatus: { min: 1, max: 1 },
  gettitle: { min: 1, max: 1 },
  getttpos: { min: 9, max: 9 },
  loadkeymap: { min: 1, max: 1 },
  restoresetup: { min: 1, max: 1 },
  logautoclosemode: { min: 1, max: 1 },
  loginfo: { min: 1, max: 1 },
  logwrite: { min: 1, max: 1 },
  logopen: { min: 3, max: 7 },
  logrotate: { min: 1, max: 2 },
  bplussend: { min: 1, max: 1 },
  kmtget: { min: 1, max: 1 },
  kmtsend: { min: 1, max: 1 },
  quickvansend: { min: 1, max: 1 },
  scprecv: { min: 1, max: 2 },
  scpsend: { min: 1, max: 2 },
  recvfile: { min: 3, max: 3 },
  sendfile: { min: 2, max: 2 },
  sendkcode: { min: 2, max: 2 },
  xmodemrecv: { min: 3, max: 3 },
  xmodemsend: { min: 2, max: 2 },
  ymodemsend: { min: 1, max: 1 },
  zmodemsend: { min: 2, max: 2 },
  setbaud: { min: 1, max: 1 },
  setspeed: { min: 1, max: 1 },
  setdebug: { min: 1, max: 1 },
  setdtr: { min: 1, max: 1 },
  setecho: { min: 1, max: 1 },
  setflowctrl: { min: 1, max: 1 },
  setmulticastname: { min: 1, max: 1 },
  setrts: { min: 1, max: 1 },
  setserialdelaychar: { min: 1, max: 1 },
  setserialdelayline: { min: 1, max: 1 },
  setsync: { min: 1, max: 1 },
  settitle: { min: 1, max: 1 },
  showtt: { min: 1, max: 1 },
  waitn: { min: 1, max: 1 },
  waitrecv: { min: 3, max: 3 },
  waitevent: { min: 1, max: 1 },
  callmenu: { min: 1, max: 1 },

  // ── 文字列操作 ──
  strdim: { min: 2, max: 2 },
  intdim: { min: 2, max: 2 },
  strconcat: { min: 2, max: 2 },
  int2str: { min: 2, max: 2 },
  str2int: { min: 2, max: 2 },
  str2code: { min: 2, max: 2 },
  code2str: { min: 2, max: 2 },
  tolower: { min: 2, max: 2 },
  toupper: { min: 2, max: 2 },
  strscan: { min: 2, max: 2 },
  strmatch: { min: 2, max: 2 },
  strcompare: { min: 2, max: 2 },
  strtrim: { min: 2, max: 2 },
  strlen: { min: 1, max: 1 },
  strlength: { min: 1, max: 1 },
  strcopy: { min: 4, max: 4 },
  strinsert: { min: 3, max: 3 },
  strremove: { min: 3, max: 3 },
  strreplace: { min: 4, max: 4 },
  strsplit: { min: 2, max: 3 },
  strjoin: { min: 2, max: 3 },
  strspecial: { min: 1, max: 2 },
  expandenv: { min: 1, max: 2 },
  getenv: { min: 2, max: 2 },
  setenv: { min: 2, max: 2 },

  // ── ファイル操作 ──
  basename: { min: 2, max: 2 },
  dirname: { min: 2, max: 2 },
  fileclose: { min: 1, max: 1 },
  fileopen: { min: 3, max: 4 },
  filemarkptr: { min: 1, max: 1 },
  fileconcat: { min: 2, max: 2 },
  filecopy: { min: 2, max: 2 },
  filecreate: { min: 2, max: 2 },
  filedelete: { min: 1, max: 1 },
  filerename: { min: 2, max: 2 },
  filesearch: { min: 1, max: 1 },
  filetruncate: { min: 2, max: 2 },
  filelock: { min: 1, max: 2 },
  fileunlock: { min: 1, max: 1 },
  filewrite: { min: 2, max: 2 },
  filewriteln: { min: 2, max: 2 },
  fileread: { min: 3, max: 3 },
  filereadln: { min: 2, max: 2 },
  filestrseek: { min: 2, max: 2 },
  filestrseek2: { min: 2, max: 2 },
  fileseek: { min: 3, max: 3 },
  fileseekback: { min: 1, max: 1 },
  filestat: { min: 2, max: 4 },
  findfirst: { min: 3, max: 3 },
  findnext: { min: 2, max: 2 },
  findclose: { min: 1, max: 1 },
  foldercreate: { min: 1, max: 1 },
  folderdelete: { min: 1, max: 1 },
  foldersearch: { min: 1, max: 1 },
  getdir: { min: 1, max: 1 },
  getfileattr: { min: 1, max: 1 },
  makepath: { min: 3, max: 3 },
  setdir: { min: 1, max: 1 },
  setfileattr: { min: 2, max: 2 },

  // ── パスワード ──
  delpassword: { min: 2, max: 2 },
  delpassword2: { min: 2, max: 2 },
  ispassword: { min: 2, max: 2 },
  ispassword2: { min: 2, max: 2 },
  setpassword: { min: 3, max: 3 },
  setpassword2: { min: 4, max: 4 },
  getpassword: { min: 3, max: 3 },
  getpassword2: { min: 4, max: 4 },

  // ── ダイアログ・その他 ──
  beep: { min: 0, max: 1 },
  messagebox: { min: 2, max: 3 },
  inputbox: { min: 2, max: 4 },
  passwordbox: { min: 2, max: 3 },
  yesnobox: { min: 2, max: 3 },
  statusbox: { min: 2, max: 3 },
  dirnamebox: { min: 1, max: 2 },
  filenamebox: { min: 1, max: 3 },
  getdate: { min: 1, max: 3 },
  gettime: { min: 1, max: 3 },
  getver: { min: 1, max: 2 },
  getttdir: { min: 1, max: 1 },
  getspecialfolder: { min: 2, max: 2 },
  getipv4addr: { min: 2, max: 2 },
  getipv6addr: { min: 2, max: 2 },
  ifdefined: { min: 1, max: 1 },
  setdate: { min: 1, max: 1 },
  settime: { min: 1, max: 1 },
  setexitcode: { min: 1, max: 1 },
  setdlgpos: { min: 0, max: 5 },
  show: { min: 1, max: 1 },
  random: { min: 2, max: 2 },
  rotateleft: { min: 3, max: 3 },
  rotateright: { min: 3, max: 3 },
  uptime: { min: 1, max: 1 },
  clipb2var: { min: 1, max: 1 },
  var2clipb: { min: 1, max: 1 },
  checksum8: { min: 2, max: 2 },
  checksum8file: { min: 2, max: 2 },
  checksum16: { min: 2, max: 2 },
  checksum16file: { min: 2, max: 2 },
  checksum32: { min: 2, max: 2 },
  checksum32file: { min: 2, max: 2 },
  crc16: { min: 2, max: 2 },
  crc16file: { min: 2, max: 2 },
  crc32: { min: 2, max: 2 },
  crc32file: { min: 2, max: 2 },
  exec: { min: 1, max: 4 },
}

export function getCommandArgSpec(cmd: string): CommandArgSpec | undefined {
  return COMMAND_ARG_SPECS[cmd.toLowerCase()]
}
